// Generated by https://quicktype.io

export interface Shoptypes {
  status: number;
  data:   Data;
}

export interface Data {
  hash:        string;
  date:        string;
  vbuckIcon:   string;
  featured:    Featured;
  daily:       Daily;
  votes:       null;
  voteWinners: null;
}

export interface Daily {
  name:    string;
  entries: DailyEntry[];
}

export interface DailyEntry {
  regularPrice:        number;
  finalPrice:          number;
  bundle:              null;
  banner:              null;
  giftable:            boolean;
  refundable:          boolean;
  sortPriority:        number;
  categories:          string[];
  sectionId:           string;
  section:             Section;
  devName:             string;
  offerId:             string;
  displayAssetPath:    null | string;
  tileSize:            TileSize;
  newDisplayAssetPath: string;
  newDisplayAsset:     PurpleNewDisplayAsset;
  items:               PurpleItem[];
}

export interface PurpleItem {
  id:               string;
  name:             string;
  description:      string;
  type:             Rarity;
  rarity:           Rarity;
  series:           null;
  set:              Set | null;
  introduction:     Introduction;
  images:           ItemImages;
  variants:         null | Variant[];
  searchTags:       null;
  gameplayTags:     string[];
  metaTags:         null;
  showcaseVideo:    string;
  dynamicPakId:     null;
  displayAssetPath: null | string;
  definitionPath:   null | string;
  path:             string;
  added:            string;
  shopHistory:      string[];
}

export interface ItemImages {
  smallIcon: string;
  icon:      string;
  featured:  null | string;
  other:     Other | null;
}

export interface Other {
  background?: string;
  decal?:      string;
  coverart?:   string;
}

export interface Introduction {
  chapter:      string;
  season:       string;
  text:         string;
  backendValue: number;
}

export interface Rarity {
  value:        PurpleValue;
  displayValue: DisplayValueEnum;
  backendValue: RarityBackendValue;
}

export enum RarityBackendValue {
  AthenaBackpack = "AthenaBackpack",
  AthenaCharacter = "AthenaCharacter",
  AthenaDance = "AthenaDance",
  AthenaGlider = "AthenaGlider",
  AthenaItemWrap = "AthenaItemWrap",
  AthenaLoadingScreen = "AthenaLoadingScreen",
  AthenaMusicPack = "AthenaMusicPack",
  AthenaPickaxe = "AthenaPickaxe",
  AthenaSpray = "AthenaSpray",
  EFortRarityEpic = "EFortRarity::Epic",
  EFortRarityLegendary = "EFortRarity::Legendary",
  EFortRarityRare = "EFortRarity::Rare",
  EFortRarityUncommon = "EFortRarity::Uncommon",
}

export enum DisplayValueEnum {
  AccesorioMochilero = "Accesorio mochilero",
  AlaDelta = "Ala delta",
  Envoltorio = "Envoltorio",
  Gesto = "Gesto",
  Grafiti = "Grafiti",
  HerramientaDeRecolección = "Herramienta de recolección",
  Legendario = "Legendario",
  Música = "Música",
  PantallaDeCarga = "Pantalla de carga",
  PocoComún = "Poco común",
  Raro = "Raro",
  SerieDeMarvel = "SERIE DE MARVEL",
  SerieDeÍdolos = "Serie de ídolos",
  Traje = "Traje",
  Épico = "Épico",
}

export enum PurpleValue {
  Backpack = "backpack",
  Emote = "emote",
  Epic = "epic",
  Glider = "glider",
  Icon = "icon",
  Legendary = "legendary",
  Loadingscreen = "loadingscreen",
  Marvel = "marvel",
  Music = "music",
  Outfit = "outfit",
  Pickaxe = "pickaxe",
  Rare = "rare",
  Spray = "spray",
  Uncommon = "uncommon",
  Wrap = "wrap",
}

export interface Set {
  value:        string;
  text:         string;
  backendValue: string;
}

export interface PurpleNewDisplayAsset {
  id:                string;
  cosmeticId:        null | string;
  materialInstances: MaterialInstance[];
}

export interface MaterialInstance {
  id:       string;
  images:   MaterialInstanceImages;
  colors:   Colors;
  scalings: { [key: string]: number };
  flags:    null;
}

export interface Colors {
  Background_Color_A:    string;
  Background_Color_B:    string;
  FallOff_Color?:        string;
  MF_RadialCoordinates?: MFRadialCoordinates;
}

export enum MFRadialCoordinates {
  Bcbc00Ff = "bcbc00ff",
  The000000Ff = "000000ff",
}

export interface MaterialInstanceImages {
  OfferImage: string;
  Background: string;
}

export interface Section {
  id:                             string;
  name:                           Name;
  index:                          number;
  landingPriority:                number;
  sortOffersByOwnership:          boolean;
  showIneligibleOffers:           boolean;
  showIneligibleOffersIfGiftable: boolean;
  showTimer:                      boolean;
  enableToastNotification:        boolean;
  hidden:                         boolean;
}

export enum Name {
  Destacados = "Destacados",
  Diario = "Diario",
  Marvel = "Marvel",
  MásOfertas = "Más ofertas",
  NaomiOsaka = "Naomi Osaka",
}

export enum TileSize {
  DoubleWide = "DoubleWide",
  Normal = "Normal",
  Small = "Small",
  TripleWide = "TripleWide",
}

export interface Featured {
  name:    string;
  entries: FeaturedEntry[];
}

export interface FeaturedEntry {
  regularPrice:        number;
  finalPrice:          number;
  bundle:              Bundle | null;
  banner:              Banner | null;
  giftable:            boolean;
  refundable:          boolean;
  sortPriority:        number;
  categories:          string[];
  sectionId:           string;
  section:             Section;
  devName:             string;
  offerId:             string;
  displayAssetPath:    null | string;
  tileSize:            TileSize;
  newDisplayAssetPath: string;
  newDisplayAsset:     FluffyNewDisplayAsset;
  items:               FluffyItem[];
}

export interface Banner {
  value:        string;
  intensity:    Intensity;
  backendValue: string;
}

export enum Intensity {
  High = "High",
  Low = "Low",
}

export interface Bundle {
  name:  string;
  info:  string;
  image: string;
}

export interface FluffyItem {
  id:                      string;
  name:                    string;
  description:             string;
  type:                    Rarity;
  rarity:                  Rarity;
  series:                  Series | null;
  set:                     Set | null;
  introduction:            Introduction | null;
  images:                  ItemImages;
  variants:                Variant[] | null;
  searchTags:              string[] | null;
  gameplayTags:            string[];
  metaTags:                string[] | null;
  showcaseVideo:           null | string;
  dynamicPakId:            null;
  displayAssetPath:        null | string;
  definitionPath:          null | string;
  path:                    string;
  added:                   string;
  shopHistory:             string[];
  itemPreviewHeroPath?:    string;
  builtInEmoteIds?:        string[];
  customExclusiveCallout?: string;
}

export interface Series {
  value:        DisplayValueEnum;
  image:        null | string;
  colors:       Color[];
  backendValue: SeriesBackendValue;
}

export enum SeriesBackendValue {
  CreatorCollabSeries = "CreatorCollabSeries",
  MarvelSeries = "MarvelSeries",
}

export enum Color {
  B30102Ff = "b30102ff",
  D60203Ff = "d60203ff",
  Ed1C24Ff = "ed1c24ff",
  The000F2Bff = "000f2bff",
  The004C71Ff = "004c71ff",
  The025253Ff = "025253ff",
  The280102Ff = "280102ff",
  The2Bc9Caff = "2bc9caff",
  The5Cf2F3Ff = "5cf2f3ff",
  The610709Ff = "610709ff",
}

export interface Variant {
  channel: Channel;
  type:    string;
  options: Option[] ;
}

export enum Channel {
  Emissive = "Emissive",
  Material = "Material",
  Mesh = "Mesh",
  Particle = "Particle",
  Parts = "Parts",
}

export interface Option {
  tag:   string;
  name:  string;
  image: string;
}

export interface FluffyNewDisplayAsset {
  id:                string;
  cosmeticId:        null | string;
  materialInstances: MaterialInstance[];
}




